#!/usr/bin/env bash
# Compose .env from profiles and hot-apply to the running backend.
# Usage: ./switch.sh [llm=local|api] [infra=ucl|h100] [pipeline_mode=auto_scientist|hill_climbing]   (no args: show current)
set -euo pipefail
cd "$(dirname "$0")"
STATE=env-profiles/current
[ -f "$STATE" ] && . "$STATE"
LLM="${LLM:-api}"; INFRA="${INFRA:-ucl}"
# PIPELINE_MODE is preserved from env-profiles/current across recomposes (it is
# set out-of-band by the /api/profile mode switch, not by an env-profiles/*.env
# fragment). Sourcing $STATE above already populated it if present.
PIPELINE_MODE="${PIPELINE_MODE:-}"
COMPOSE_ONLY=false
[ "${1:-}" = "--compose-only" ] && { COMPOSE_ONLY=true; shift; }


for arg in "$@"; do
  case "$arg" in
    llm=local|llm=api) LLM="${arg#llm=}" ;;
    infra=ucl|infra=h100) INFRA="${arg#infra=}" ;;
    pipeline_mode=auto_scientist|pipeline_mode=hill_climbing) PIPELINE_MODE="${arg#pipeline_mode=}" ;;
    *) echo "usage: ./switch.sh [llm=local|api] [infra=ucl|h100] [pipeline_mode=auto_scientist|hill_climbing]" >&2; exit 1 ;;
  esac
done

if [ "$#" -eq 0 ]; then
  echo "current: llm=$LLM infra=$INFRA pipeline_mode=${PIPELINE_MODE:-auto_scientist}   (pass args to change)"
  exit 0
fi

LLM_F="env-profiles/llm.$LLM.env"
INFRA_F="env-profiles/infra.$INFRA.env"
for f in env-profiles/base.env "$LLM_F" "$INFRA_F"; do
  [ -f "$f" ] || { echo "missing $f" >&2; exit 1; }
done
grep -qE '^INFRA_SERVER_URL=.+' "$INFRA_F" || { echo "error: $INFRA_F has empty INFRA_SERVER_URL" >&2; exit 1; }

{
  echo "# GENERATED by switch.sh — edit env-profiles/*, not this file"
  echo "# profile: llm=$LLM infra=$INFRA pipeline_mode=${PIPELINE_MODE:-auto_scientist}"
  cat env-profiles/base.env; echo
  cat "$LLM_F"; echo
  cat "$INFRA_F"; echo
  # PIPELINE_MODE is not part of any fragment; carry it into the runtime env so
  # the app boots in the selected mode (the engine reads os.environ PIPELINE_MODE).
  [ -n "$PIPELINE_MODE" ] && echo "PIPELINE_MODE=$PIPELINE_MODE"
} > .env
[ -f .onemancompany/.env ] && cat .env > .onemancompany/.env
# Persist LLM/INFRA and (if set) PIPELINE_MODE back to current so the next
# recompose preserves the mode rather than dropping it.
{
  printf 'LLM=%s\nINFRA=%s\n' "$LLM" "$INFRA"
  [ -n "$PIPELINE_MODE" ] && printf 'PIPELINE_MODE=%s\n' "$PIPELINE_MODE"
} > "$STATE"

if [ "$COMPOSE_ONLY" = true ]; then
  python3 - "$LLM_F" "$INFRA_F" <<'PY2'
import sys, json
u = {}
for f in sys.argv[1:]:
    for line in open(f):
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1); u[k.strip()] = v.strip()
print(json.dumps(u))
PY2
  exit 0
fi

# Hot-apply to the live backend: save_env sets os.environ (which the infra
# routes read), admin/reload rebuilds the settings singleton (LLM defaults).
PORT="${PORT:-8000}"
if curl -fsS -m 3 "http://$(hostname -f):$PORT/api/bootstrap" >/dev/null 2>&1; then
  python3 - "$LLM_F" "$INFRA_F" "$PIPELINE_MODE" <<'PY' | curl -fsS -m 10 -X POST "http://$(hostname -f):${PORT:-8000}/api/env" -H 'Content-Type: application/json' -d @- >/dev/null
import sys, json
updates = {}
for f in sys.argv[1:3]:
    for line in open(f):
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            k, v = line.split('=', 1)
            updates[k.strip()] = v.strip()
pm = sys.argv[3] if len(sys.argv) > 3 else ""
if pm:
    updates["PIPELINE_MODE"] = pm
print(json.dumps(updates))
PY
  curl -fsS -m 30 -X POST "http://$(hostname -f):$PORT/api/admin/reload" >/dev/null
  echo "switched: llm=$LLM infra=$INFRA pipeline_mode=${PIPELINE_MODE:-auto_scientist} (applied to running backend)"
else
  echo "switched: llm=$LLM infra=$INFRA pipeline_mode=${PIPELINE_MODE:-auto_scientist} (backend not running — takes effect on next start)"
fi
